# Generated by Django 5.2.9 on 2026-01-09 00:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('elog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logbook',
            options={},
        ),
        migrations.RemoveField(
            model_name='logbook',
            name='book_type',
        ),
        migrations.RemoveField(
            model_name='logbook',
            name='property_type',
        ),
        migrations.AddField(
            model_name='logbook',
            name='access_level',
            field=models.CharField(choices=[('private', 'Private (Owner only)'), ('shared', 'Shared (Group Members)'), ('public', 'Public (All Users)')], default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='logbook',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='shared_logbooks', to='auth.group'),
        ),
        migrations.AddField(
            model_name='logbook',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='permitted_logbooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
